Array
(
    [0] => stdClass Object
        (
            [date] => 2018-09-01 17:37:42
            [paypalinfo] => 
            [invoicestatus] => 0
            [driverComment] => 
            [bringgCompanyId] => 
            [requestCollection] => 
            [printerStime] => 
            [data] => {"Total":74.5,"business":[{"id":58,"name":"Australind Chinese restaurant","tel":"61897258988","email":"jayhuang175@gmail.com","paymethod":{"cash":false,"card":false,"paypal":false,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":true,"payu":false,"stripedirect":false,"paypal_express":false,"stripeconnect":false,"striperedirect":false},"paymethoddetail":{"cash":true,"card":true,"paypal":true,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"payu":false,"stripe":true},"shipping":15,"minimum":"0","dishes":[{"id":"1730","name":"Sweet & Sour Pork","price":"15","quantity":1,"o_quantity":1,"data_options":{},"total":15,"ingredients":{},"code":"obZyN","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""},{"id":"1686","name":"Boneless Honey Chicken","price":"15.50","quantity":1,"o_quantity":1,"data_options":{},"total":15.5,"ingredients":{},"code":"bnbby","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""},{"id":"1739","name":"Pork Rib with Sweet & Sour Sauce","price":"17","quantity":1,"o_quantity":1,"data_options":{},"total":17,"ingredients":{},"code":"IKRt4","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""},{"id":"1757","name":"Special Fried Rice","price":"0.00","quantity":1,"o_quantity":1,"data_options":{"87,301":false,"87,302":true},"total":10,"ingredients":{},"code":"ADALK","business":"58","options":"_@_Choose Size@u@Large    $10.00","optionsOnlytext":"Large","optionsChoiceId":"302","extras":[{"choiceId":302,"choiceName":"Large","price":"10","optionId":87}],"comments":"No prawns please","strOptions":"<span><strong>Choose Size<\/strong><br><span>Large $10.00<br><\/span><\/span>"},{"id":"1663","name":"Prawn Crackers","price":"2","quantity":1,"o_quantity":1,"data_options":{},"total":2,"ingredients":{},"code":"dQ6ts","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""}],"twiliophone":null,"acceptsms":false,"header":"https:\/\/res.cloudinary.com\/www-townaround-com-au\/image\/upload\/f_auto,q_auto\/v1533899123\/dkx1uzcxjkoa50ohidvs.jpg","currency":"$","paydata":"ch_1D5VY0KFiujq1hZXdFkIa8KJ"}],"buyer":{"id":"94","address":"8\/1 Beela Road, Brunswick WA, Australia","city":"1","cityname":"Perth","tax":"0","taxtype":"2","deliveryType":"delivery","deliverydate":"9-1-2018 17:45","comments":"","name":"MasterTJ","lastname2":null,"email":"randomize1995@gmail.com","colony":null,"tel":"0432747585","checkoutfields":["Name","Email","Full Address","APT\/Suit","Phone","Discount Coupon"],"street":"8\/1 Beela Road, Brunswick WA, Australia","tips":"0.00","location":{"zip":"6224","cityname":"Brunswick","lat":-33.253406,"lng":115.8433103}},"customslug":"Australind-Chinese-restaurant","discountprice":"","grandtotal":"74.50","reserve":{},"reserveFee":0,"reservePrice":{},"reserveQty":{},"reservepaymethod":{"payu":false,"cash":false,"card":false,"paypal":false,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":false,"paypalpro":false,"paygistix":false},"reservepaymethoddetails":{"payu":true,"cash":true,"card":true,"paypal":true,"paypaladaptive":true,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":true,"paypalpro":true,"paygistix":true},"reservestatus":false,"servicefee":0,"servicefeeTotal":"0.00","servicefeeTotal1":0,"tax":"0.00","total":74.5,"twilioenabledclient":false,"searchinfo":{},"discountoffer":false}
            [globalResult] => 
            [requestcollectiondata] => 
            [twilioenabled] => 
            [printerComment] => 
            [payeezyResult] => 
            [aTrnxCode] => 
            [scriptid] => 0
            [driverBringId] => 
            [aTrnxStatement] => 
            [soundstatus] => 0
            [paypalproResult] => 
            [id] => 184
            [bringgAccessToken] => 
            [countDown] => 40
            [collectionId] => 
            [transactiumStatus] => 
            [setTime] => 0
            [recentdata] => {"user":{"name":"M"},"business":{"id":58,"name":"Australind Chinese restaurant"}}
            [merchantval] => 
            [payuResult] => 
            [paypaltx] => 
            [btransResult] => 
            [pxResult] => 
            [transactiumTid] => 
            [isChecked] => 0
            [parentId] => 0
            [bringgCustomerId] => 
            [pxUserid] => 
            [bringgOrderId] => 0
            [driverId] => 7
            [deliverytime] => 
            [stripeResult] => ch_1D5VY0KFiujq1hZXdFkIa8KJ
            [comment] => 
            [bringgSecretToken] => 
            [user] => 94
            [status] => 11
        )

    [1] => stdClass Object
        (
            [date] => 2018-08-10 19:06:36
            [paypalinfo] => 
            [invoicestatus] => 0
            [driverComment] => 
            [bringgCompanyId] => 
            [requestCollection] => 
            [printerStime] => 
            [data] => {"Total":57,"business":[{"id":58,"name":"Australind Chinese restaurant","tel":"61897258988","email":"jayhuang175@gmail.com","paymethod":{"cash":false,"card":false,"paypal":false,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":true,"payu":false,"stripedirect":false,"paypal_express":false,"stripeconnect":false,"striperedirect":false},"paymethoddetail":{"cash":true,"card":true,"paypal":true,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"payu":false,"stripe":true},"shipping":10,"minimum":"0","dishes":[{"id":"1686","name":"Boneless Honey Chicken","price":"15.50","quantity":1,"o_quantity":1,"data_options":{},"total":15.5,"ingredients":{},"code":"t6j94","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""},{"id":"1778","name":"Beef with Cashew Nuts","price":"15.50","quantity":1,"o_quantity":1,"data_options":{},"total":15.5,"ingredients":{},"code":"nFBWF","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""},{"id":"1757","name":"Special Fried Rice","price":"0.00","quantity":1,"o_quantity":1,"data_options":{"87,301":false,"87,302":true},"total":10,"ingredients":{},"code":"gLnEV","business":"58","options":"_@_Choose Size@u@Large    $10.00","optionsOnlytext":"Large","optionsChoiceId":"302","extras":[{"choiceId":302,"choiceName":"Large","price":"10","optionId":87}],"strOptions":"<span><strong>Choose Size<\/strong><br><span>Large $10.00<br><\/span><\/span>"},{"id":"1662","name":"Mini Spring Rolls (3)","price":"6","quantity":1,"o_quantity":1,"data_options":{},"total":6,"ingredients":{},"code":"3gt5q","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""}],"twiliophone":null,"acceptsms":false,"header":"https:\/\/res.cloudinary.com\/www-townaround-com-au\/image\/upload\/f_auto,q_auto\/v1531734304\/w3bmjitlfndlt5liaqe6.jpg","currency":"$","paydata":"ch_1CxYRyKFiujq1hZXeO9VE9ZR"}],"buyer":{"id":"52","address":"11 Avon Gardens, Millbridge WA 6232, Australia","city":"1","cityname":"Perth","tax":"0","taxtype":"2","deliveryType":"delivery","deliverydate":"8-10-2018 19:15","comments":"","name":"Tyler","lastname2":null,"email":"tyler.spalds@gmail.com","colony":null,"tel":"0467889537","checkoutfields":["Name","Email","Full Address","APT\/Suit","Phone","Discount Coupon"],"street":"11 Avon Gardens, Millbridge WA 6232, Australia","tips":"0.00","location":{"lat":-33.30857,"lng":115.7314126,"zip":"6232","cityname":"Millbridge"}},"customslug":"Australind-Chinese-restaurant","discountprice":"","grandtotal":"57.00","reserve":{},"reserveFee":0,"reservePrice":{},"reserveQty":{},"reservepaymethod":{"payu":false,"cash":false,"card":false,"paypal":false,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":false,"paypalpro":false,"paygistix":false},"reservepaymethoddetails":{"payu":true,"cash":true,"card":true,"paypal":true,"paypaladaptive":true,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":true,"paypalpro":true,"paygistix":true},"reservestatus":false,"servicefee":0,"servicefeeTotal":"0.00","servicefeeTotal1":0,"tax":"0.00","total":57,"twilioenabledclient":false,"searchinfo":{},"discountoffer":false}
            [globalResult] => 
            [requestcollectiondata] => 
            [twilioenabled] => 
            [printerComment] => 
            [payeezyResult] => 
            [aTrnxCode] => 
            [scriptid] => 0
            [driverBringId] => 
            [aTrnxStatement] => 
            [soundstatus] => 0
            [paypalproResult] => 
            [id] => 148
            [bringgAccessToken] => 
            [countDown] => 30
            [collectionId] => 
            [transactiumStatus] => 
            [setTime] => 0
            [recentdata] => {"user":{"name":"T"},"business":{"id":58,"name":"Australind Chinese restaurant"}}
            [merchantval] => 
            [payuResult] => 
            [paypaltx] => 
            [btransResult] => 
            [pxResult] => 
            [transactiumTid] => 
            [isChecked] => 0
            [parentId] => 0
            [bringgCustomerId] => 
            [pxUserid] => 
            [bringgOrderId] => 0
            [driverId] => 7
            [deliverytime] => 
            [stripeResult] => ch_1CxYRyKFiujq1hZXeO9VE9ZR
            [comment] => 
            [bringgSecretToken] => 
            [user] => 52
            [status] => 11
        )

    [2] => stdClass Object
        (
            [date] => 2018-09-01 17:53:52
            [paypalinfo] => 
            [invoicestatus] => 0
            [driverComment] => 
            [bringgCompanyId] => 
            [requestCollection] => 
            [printerStime] => 
            [data] => {"Total":46,"business":[{"id":58,"name":"Australind Chinese restaurant","tel":"61897258988","email":"jayhuang175@gmail.com","paymethod":{"cash":false,"card":false,"paypal":false,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":true,"payu":false,"stripedirect":false,"paypal_express":false,"stripeconnect":false,"striperedirect":false},"paymethoddetail":{"cash":true,"card":true,"paypal":true,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"payu":false},"shipping":7,"minimum":"0","dishes":[{"id":"1750","name":"Combination Omelette","price":"15.50","quantity":1,"o_quantity":1,"data_options":{},"total":15.5,"ingredients":{},"code":"f1dgv","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""},{"id":"1757","name":"Special Fried Rice","price":"0.00","quantity":1,"o_quantity":1,"data_options":{"87,301":false,"87,302":true},"total":10,"ingredients":{},"code":"J3FqS","business":"58","options":"_@_Choose Size@u@Large    $10.00","optionsOnlytext":"Large","optionsChoiceId":"302","extras":[{"choiceId":302,"choiceName":"Large","price":"10","optionId":87}],"strOptions":"<span><strong>Choose Size<\/strong><br><span>Large $10.00<br><\/span><\/span>"},{"id":"1758","name":"Fried Soft Noodle (Egg noodle)","price":"13.50","quantity":1,"o_quantity":1,"data_options":{},"total":13.5,"ingredients":{},"code":"DEgF5","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""}],"twiliophone":null,"acceptsms":false,"header":"https:\/\/res.cloudinary.com\/www-townaround-com-au\/image\/upload\/f_auto,q_auto\/v1533899123\/dkx1uzcxjkoa50ohidvs.jpg","currency":"$","paydata":"ch_1D5VneKFiujq1hZXqovuAl4z"}],"buyer":{"id":"96","address":"3 MacKenzie Place, Australind WA, Australia","city":"1","cityname":"Perth","tax":"0","taxtype":"2","deliveryType":"delivery","deliverydate":"9-1-2018 18:00","comments":"","name":"Mark","lastname2":null,"email":"marksmith1984@live.com.au","api":"Please come to the front door in carport","colony":null,"tel":"0421842310","checkoutfields":["Name","Email","Full Address","APT\/Suit","Phone","Discount Coupon"],"street":"3 MacKenzie Place, Australind WA, Australia","tips":"0.00","location":{"lat":-33.2725343,"lng":115.7260139,"zip":"6233","cityname":"Australind"}},"customslug":"Australind-Chinese-restaurant","discountprice":"","grandtotal":"46.00","reserve":{},"reserveFee":0,"reservePrice":{},"reserveQty":{},"reservepaymethod":{"payu":false,"cash":false,"card":false,"paypal":false,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":false,"paypalpro":false,"paygistix":false},"reservepaymethoddetails":{"payu":true,"cash":true,"card":true,"paypal":true,"paypaladaptive":true,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":true,"paypalpro":true,"paygistix":true},"reservestatus":false,"servicefee":0,"servicefeeTotal":"0.00","servicefeeTotal1":0,"tax":"0.00","total":46,"twilioenabledclient":false,"searchinfo":{},"discountoffer":false}
            [globalResult] => 
            [requestcollectiondata] => 
            [twilioenabled] => 
            [printerComment] => 
            [payeezyResult] => 
            [aTrnxCode] => 
            [scriptid] => 0
            [driverBringId] => 
            [aTrnxStatement] => 
            [soundstatus] => 0
            [paypalproResult] => 
            [id] => 185
            [bringgAccessToken] => 
            [countDown] => 15
            [collectionId] => 
            [transactiumStatus] => 
            [setTime] => 0
            [recentdata] => {"user":{"name":"M"},"business":{"id":58,"name":"Australind Chinese restaurant"}}
            [merchantval] => 
            [payuResult] => 
            [paypaltx] => 
            [btransResult] => 
            [pxResult] => 
            [transactiumTid] => 
            [isChecked] => 0
            [parentId] => 0
            [bringgCustomerId] => 
            [pxUserid] => 
            [bringgOrderId] => 0
            [driverId] => 7
            [deliverytime] => 
            [stripeResult] => ch_1D5VneKFiujq1hZXqovuAl4z
            [comment] => 
            [bringgSecretToken] => 
            [user] => 96
            [status] => 11
        )

    [3] => stdClass Object
        (
            [date] => 2018-09-01 18:03:19
            [paypalinfo] => 
            [invoicestatus] => 0
            [driverComment] => 
            [bringgCompanyId] => 
            [requestCollection] => 
            [printerStime] => 
            [data] => {"Total":32.5,"business":[{"id":58,"name":"Australind Chinese restaurant","tel":"61897258988","email":"jayhuang175@gmail.com","paymethod":{"cash":false,"card":false,"paypal":false,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":true,"payu":false,"stripedirect":false,"paypal_express":false,"stripeconnect":false,"striperedirect":false},"paymethoddetail":{"cash":true,"card":true,"paypal":true,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"payu":false,"stripe":true},"shipping":7,"minimum":"0","dishes":[{"id":"1776","name":"Beef with Chilli","price":"15.50","quantity":1,"o_quantity":1,"data_options":{},"total":15.5,"ingredients":{},"code":"viwcI","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""},{"id":"1757","name":"Special Fried Rice","price":"0.00","quantity":1,"o_quantity":1,"data_options":{"87,301":false,"87,302":true},"total":10,"ingredients":{},"code":"7NqyV","business":"58","options":"_@_Choose Size@u@Large    $10.00","optionsOnlytext":"Large","optionsChoiceId":"302","extras":[{"choiceId":302,"choiceName":"Large","price":"10","optionId":87}],"strOptions":"<span><strong>Choose Size<\/strong><br><span>Large $10.00<br><\/span><\/span>"}],"twiliophone":null,"acceptsms":false,"header":"https:\/\/res.cloudinary.com\/www-townaround-com-au\/image\/upload\/f_auto,q_auto\/v1533899123\/dkx1uzcxjkoa50ohidvs.jpg","currency":"$","paydata":"ch_1D5VwnKFiujq1hZX0bKODFjL"}],"buyer":{"id":"74","address":"15 Hoskins Way, Australind WA 6233, Australia","city":"1","cityname":"Perth","tax":"0","taxtype":"2","deliveryType":"delivery","deliverydate":"ASAP","comments":"","name":"Ben","lastname2":null,"email":"greenie3@westnet.com.au","colony":null,"tel":"0408738434","checkoutfields":["Name","Email","Full Address","APT\/Suit","Phone","Discount Coupon"],"street":"15 Hoskins Way, Australind WA 6233, Australia","tips":"0.00","location":{"lat":-33.2656932,"lng":115.7290884,"zip":"6233","cityname":"Australind"}},"customslug":"Australind-Chinese-restaurant","discountprice":"","grandtotal":"32.50","reserve":{},"reserveFee":0,"reservePrice":{},"reserveQty":{},"reservepaymethod":{"payu":false,"cash":false,"card":false,"paypal":false,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":false,"paypalpro":false,"paygistix":false},"reservepaymethoddetails":{"payu":true,"cash":true,"card":true,"paypal":true,"paypaladaptive":true,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":true,"paypalpro":true,"paygistix":true},"reservestatus":false,"servicefee":0,"servicefeeTotal":"0.00","servicefeeTotal1":0,"tax":"0.00","total":32.5,"twilioenabledclient":false,"searchinfo":{},"discountoffer":false}
            [globalResult] => 
            [requestcollectiondata] => 
            [twilioenabled] => 
            [printerComment] => 
            [payeezyResult] => 
            [aTrnxCode] => 
            [scriptid] => 0
            [driverBringId] => 
            [aTrnxStatement] => 
            [soundstatus] => 0
            [paypalproResult] => 
            [id] => 186
            [bringgAccessToken] => 
            [countDown] => 20
            [collectionId] => 
            [transactiumStatus] => 
            [setTime] => 0
            [recentdata] => {"user":{"name":"B"},"business":{"id":58,"name":"Australind Chinese restaurant"}}
            [merchantval] => 
            [payuResult] => 
            [paypaltx] => 
            [btransResult] => 
            [pxResult] => 
            [transactiumTid] => 
            [isChecked] => 0
            [parentId] => 0
            [bringgCustomerId] => 
            [pxUserid] => 
            [bringgOrderId] => 0
            [driverId] => 7
            [deliverytime] => 
            [stripeResult] => ch_1D5VwnKFiujq1hZX0bKODFjL
            [comment] => 
            [bringgSecretToken] => 
            [user] => 74
            [status] => 11
        )

    [4] => stdClass Object
        (
            [date] => 2018-08-18 18:34:30
            [paypalinfo] => 
            [invoicestatus] => 0
            [driverComment] => 
            [bringgCompanyId] => 
            [requestCollection] => 
            [printerStime] => 
            [data] => {"Total":50.5,"business":[{"id":58,"name":"Australind Chinese restaurant","tel":"61897258988","email":"jayhuang175@gmail.com","paymethod":{"cash":false,"card":false,"paypal":false,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":true,"payu":false,"stripedirect":false,"paypal_express":false,"stripeconnect":false,"striperedirect":false},"paymethoddetail":{"cash":true,"card":true,"paypal":true,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"payu":false},"shipping":10,"minimum":"0","dishes":[{"id":"1782","name":"Szechuan Beef","price":"15.50","quantity":1,"o_quantity":1,"data_options":{},"total":15.5,"ingredients":{},"code":"DoCDN","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""},{"id":"1724","name":"Pork Chow Mein","price":"15","quantity":1,"o_quantity":1,"data_options":{},"total":15,"ingredients":{},"code":"3Gq90","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""},{"id":"1757","name":"Special Fried Rice","price":"0.00","quantity":1,"o_quantity":1,"data_options":{"87,301":false,"87,302":true},"total":10,"ingredients":{},"code":"BokDb","business":"58","options":"_@_Choose Size@u@Large    $10.00","optionsOnlytext":"Large","optionsChoiceId":"302","extras":[{"choiceId":302,"choiceName":"Large","price":"10","optionId":87}],"strOptions":"<span><strong>Choose Size<\/strong><br><span>Large $10.00<br><\/span><\/span>"}],"twiliophone":null,"acceptsms":false,"header":"https:\/\/res.cloudinary.com\/www-townaround-com-au\/image\/upload\/f_auto,q_auto\/v1533899123\/dkx1uzcxjkoa50ohidvs.jpg","currency":"$","paydata":"ch_1D0RlIKFiujq1hZXfnVLBQh6"}],"buyer":{"id":"74","address":"15 Hoskins Way, Australind WA 6233, Australia","city":"1","cityname":"Perth","tax":"0","taxtype":"2","deliveryType":"delivery","deliverydate":"8-18-2018 18:45","comments":"","name":"Ben","lastname2":null,"email":"greenie3@westnet.com.au","colony":null,"tel":"0408738434","checkoutfields":["Name","Email","Full Address","APT\/Suit","Phone","Discount Coupon"],"street":"15 Hoskins Way, Australind WA 6233, Australia","tips":"0.00","location":{"lat":-33.2656932,"lng":115.7290884,"zip":"6233","cityname":"Australind"}},"customslug":"Australind-Chinese-restaurant","discountprice":"","grandtotal":"50.50","reserve":{},"reserveFee":0,"reservePrice":{},"reserveQty":{},"reservepaymethod":{"payu":false,"cash":false,"card":false,"paypal":false,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":false,"paypalpro":false,"paygistix":false},"reservepaymethoddetails":{"payu":true,"cash":true,"card":true,"paypal":true,"paypaladaptive":true,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":true,"paypalpro":true,"paygistix":true},"reservestatus":false,"servicefee":0,"servicefeeTotal":"0.00","servicefeeTotal1":0,"tax":"0.00","total":50.5,"twilioenabledclient":false,"searchinfo":{},"discountoffer":false}
            [globalResult] => 
            [requestcollectiondata] => 
            [twilioenabled] => 
            [printerComment] => 
            [payeezyResult] => 
            [aTrnxCode] => 
            [scriptid] => 0
            [driverBringId] => 
            [aTrnxStatement] => 
            [soundstatus] => 0
            [paypalproResult] => 
            [id] => 162
            [bringgAccessToken] => 
            [countDown] => 30
            [collectionId] => 
            [transactiumStatus] => 
            [setTime] => 0
            [recentdata] => {"user":{"name":"B"},"business":{"id":58,"name":"Australind Chinese restaurant"}}
            [merchantval] => 
            [payuResult] => 
            [paypaltx] => 
            [btransResult] => 
            [pxResult] => 
            [transactiumTid] => 
            [isChecked] => 0
            [parentId] => 0
            [bringgCustomerId] => 
            [pxUserid] => 
            [bringgOrderId] => 0
            [driverId] => 7
            [deliverytime] => 
            [stripeResult] => ch_1D0RlIKFiujq1hZXfnVLBQh6
            [comment] => 
            [bringgSecretToken] => 
            [user] => 74
            [status] => 11
        )

    [5] => stdClass Object
        (
            [date] => 2018-08-25 18:34:10
            [paypalinfo] => 
            [invoicestatus] => 0
            [driverComment] => 
            [bringgCompanyId] => 
            [requestCollection] => 
            [printerStime] => 
            [data] => {"Total":43.4,"business":[{"id":58,"name":"Australind Chinese restaurant","tel":"61897258988","email":"jayhuang175@gmail.com","paymethod":{"cash":false,"card":false,"paypal":false,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":true,"payu":false,"stripedirect":false,"paypal_express":false,"stripeconnect":false,"striperedirect":false},"paymethoddetail":{"cash":true,"card":true,"paypal":true,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"payu":false,"stripe":true},"shipping":12.9,"minimum":"0","dishes":[{"id":"1722","name":"Chicken Chow Mein","price":"15","quantity":1,"o_quantity":1,"data_options":{},"total":15,"ingredients":{},"code":"Rvex1","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""},{"id":"1750","name":"Combination Omelette","price":"15.50","quantity":1,"o_quantity":1,"data_options":{},"total":15.5,"ingredients":{},"code":"6wDR3","business":"58","options":"","optionsOnlytext":"","optionsChoiceId":"","extras":[],"strOptions":""}],"twiliophone":null,"acceptsms":false,"header":"https:\/\/res.cloudinary.com\/www-townaround-com-au\/image\/upload\/f_auto,q_auto\/v1533899123\/dkx1uzcxjkoa50ohidvs.jpg","currency":"$","paydata":"ch_1D2z5oKFiujq1hZXeS4nqHLN"}],"buyer":{"id":"85","address":"2 Pituri Close, Glen Iris WA, Australia","city":"1","cityname":"Perth","tax":"0","taxtype":"2","deliveryType":"delivery","deliverydate":"8-25-2018 18:45","comments":"","name":"Leon","lastname2":null,"email":"leonmateariki@yahoo.com","colony":null,"tel":"0449667600","checkoutfields":["Name","Email","Full Address","APT\/Suit","Phone","Discount Coupon"],"street":"2 Pituri Close, Glen Iris WA, Australia","tips":"0.00","location":{"zip":"6230","cityname":"Glen Iris","lat":-33.3402781,"lng":115.6817197}},"customslug":"Australind-Chinese-restaurant","discountprice":"","grandtotal":"43.40","reserve":{},"reserveFee":0,"reservePrice":{},"reserveQty":{},"reservepaymethod":{"payu":false,"cash":false,"card":false,"paypal":false,"paypaladaptive":false,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":false,"paypalpro":false,"paygistix":false},"reservepaymethoddetails":{"payu":true,"cash":true,"card":true,"paypal":true,"paypaladaptive":true,"authorize":false,"braintree":false,"mercury":false,"worldpay":false,"mercadopago":false,"transactium":false,"pexpress":false,"maksekeskus":false,"voguepay":false,"skrill":false,"payeezy":false,"stripe":true,"paypalpro":true,"paygistix":true},"reservestatus":false,"servicefee":0,"servicefeeTotal":"0.00","servicefeeTotal1":0,"tax":"0.00","total":43.4,"twilioenabledclient":false,"searchinfo":{},"discountoffer":false}
            [globalResult] => 
            [requestcollectiondata] => 
            [twilioenabled] => 
            [printerComment] => 
            [payeezyResult] => 
            [aTrnxCode] => 
            [scriptid] => 0
            [driverBringId] => 
            [aTrnxStatement] => 
            [soundstatus] => 0
            [paypalproResult] => 
            [id] => 176
            [bringgAccessToken] => 
            [countDown] => 30
            [collectionId] => 
            [transactiumStatus] => 
            [setTime] => 0
            [recentdata] => {"user":{"name":"L"},"business":{"id":58,"name":"Australind Chinese restaurant"}}
            [merchantval] => 
            [payuResult] => 
            [paypaltx] => 
            [btransResult] => 
            [pxResult] => 
            [transactiumTid] => 
            [isChecked] => 0
            [parentId] => 0
            [bringgCustomerId] => 
            [pxUserid] => 
            [bringgOrderId] => 0
            [driverId] => 13
            [deliverytime] => 
            [stripeResult] => ch_1D2z5oKFiujq1hZXeS4nqHLN
            [comment] => 
            [bringgSecretToken] => 
            [user] => 85
            [status] => 11
        )

)
